// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/financedata.proto

package io.grpc.grpcinterface;

public interface DataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:financedata.DataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
