// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financedata.proto

package io.grpc.grpcinterface;

/**
 * Protobuf type {@code financedata.DataResponse}
 */
public final class DataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:financedata.DataResponse)
    DataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataResponse.newBuilder() to construct.
  private DataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataResponse() {
    message_ = "";
    startTime_ = "";
    endTime_ = "";
    notes_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DataResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.grpcinterface.GetDataProto.internal_static_financedata_DataResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetMapListData();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.grpcinterface.GetDataProto.internal_static_financedata_DataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.grpcinterface.DataResponse.class, io.grpc.grpcinterface.DataResponse.Builder.class);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTTIME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object startTime_ = "";
  /**
   * <code>string startTime = 2;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public java.lang.String getStartTime() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      startTime_ = s;
      return s;
    }
  }
  /**
   * <code>string startTime = 2;</code>
   * @return The bytes for startTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartTimeBytes() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDTIME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object endTime_ = "";
  /**
   * <code>string endTime = 3;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public java.lang.String getEndTime() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endTime_ = s;
      return s;
    }
  }
  /**
   * <code>string endTime = 3;</code>
   * @return The bytes for endTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEndTimeBytes() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object notes_ = "";
  /**
   * <code>string notes = 4;</code>
   * @return The notes.
   */
  @java.lang.Override
  public java.lang.String getNotes() {
    java.lang.Object ref = notes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notes_ = s;
      return s;
    }
  }
  /**
   * <code>string notes = 4;</code>
   * @return The bytes for notes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNotesBytes() {
    java.lang.Object ref = notes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LISTDATA_FIELD_NUMBER = 5;
  private io.grpc.grpcinterface.ListOfString listData_;
  /**
   * <code>.financedata.ListOfString listData = 5;</code>
   * @return Whether the listData field is set.
   */
  @java.lang.Override
  public boolean hasListData() {
    return listData_ != null;
  }
  /**
   * <code>.financedata.ListOfString listData = 5;</code>
   * @return The listData.
   */
  @java.lang.Override
  public io.grpc.grpcinterface.ListOfString getListData() {
    return listData_ == null ? io.grpc.grpcinterface.ListOfString.getDefaultInstance() : listData_;
  }
  /**
   * <code>.financedata.ListOfString listData = 5;</code>
   */
  @java.lang.Override
  public io.grpc.grpcinterface.ListOfStringOrBuilder getListDataOrBuilder() {
    return listData_ == null ? io.grpc.grpcinterface.ListOfString.getDefaultInstance() : listData_;
  }

  public static final int MAPLISTDATA_FIELD_NUMBER = 6;
  private static final class MapListDataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.grpc.grpcinterface.ListOfString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.grpc.grpcinterface.ListOfString>newDefaultInstance(
                io.grpc.grpcinterface.GetDataProto.internal_static_financedata_DataResponse_MapListDataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.grpc.grpcinterface.ListOfString.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, io.grpc.grpcinterface.ListOfString> mapListData_;
  private com.google.protobuf.MapField<java.lang.String, io.grpc.grpcinterface.ListOfString>
  internalGetMapListData() {
    if (mapListData_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapListDataDefaultEntryHolder.defaultEntry);
    }
    return mapListData_;
  }
  public int getMapListDataCount() {
    return internalGetMapListData().getMap().size();
  }
  /**
   * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
   */
  @java.lang.Override
  public boolean containsMapListData(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMapListData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapListDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString> getMapListData() {
    return getMapListDataMap();
  }
  /**
   * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString> getMapListDataMap() {
    return internalGetMapListData().getMap();
  }
  /**
   * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
   */
  @java.lang.Override
  public /* nullable */
io.grpc.grpcinterface.ListOfString getMapListDataOrDefault(
      java.lang.String key,
      /* nullable */
io.grpc.grpcinterface.ListOfString defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString> map =
        internalGetMapListData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
   */
  @java.lang.Override
  public io.grpc.grpcinterface.ListOfString getMapListDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString> map =
        internalGetMapListData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, startTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, endTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notes_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, notes_);
    }
    if (listData_ != null) {
      output.writeMessage(5, getListData());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMapListData(),
        MapListDataDefaultEntryHolder.defaultEntry,
        6);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, startTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, endTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notes_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, notes_);
    }
    if (listData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getListData());
    }
    for (java.util.Map.Entry<java.lang.String, io.grpc.grpcinterface.ListOfString> entry
         : internalGetMapListData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.grpc.grpcinterface.ListOfString>
      mapListData__ = MapListDataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, mapListData__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.grpcinterface.DataResponse)) {
      return super.equals(obj);
    }
    io.grpc.grpcinterface.DataResponse other = (io.grpc.grpcinterface.DataResponse) obj;

    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getStartTime()
        .equals(other.getStartTime())) return false;
    if (!getEndTime()
        .equals(other.getEndTime())) return false;
    if (!getNotes()
        .equals(other.getNotes())) return false;
    if (hasListData() != other.hasListData()) return false;
    if (hasListData()) {
      if (!getListData()
          .equals(other.getListData())) return false;
    }
    if (!internalGetMapListData().equals(
        other.internalGetMapListData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getStartTime().hashCode();
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + getEndTime().hashCode();
    hash = (37 * hash) + NOTES_FIELD_NUMBER;
    hash = (53 * hash) + getNotes().hashCode();
    if (hasListData()) {
      hash = (37 * hash) + LISTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getListData().hashCode();
    }
    if (!internalGetMapListData().getMap().isEmpty()) {
      hash = (37 * hash) + MAPLISTDATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMapListData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.grpcinterface.DataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.grpcinterface.DataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.grpcinterface.DataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.grpcinterface.DataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.grpcinterface.DataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.grpcinterface.DataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.grpcinterface.DataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.grpcinterface.DataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.grpc.grpcinterface.DataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.grpc.grpcinterface.DataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.grpcinterface.DataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.grpcinterface.DataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.grpcinterface.DataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code financedata.DataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:financedata.DataResponse)
      io.grpc.grpcinterface.DataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.grpcinterface.GetDataProto.internal_static_financedata_DataResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMapListData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableMapListData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.grpcinterface.GetDataProto.internal_static_financedata_DataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.grpcinterface.DataResponse.class, io.grpc.grpcinterface.DataResponse.Builder.class);
    }

    // Construct using io.grpc.grpcinterface.DataResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      message_ = "";
      startTime_ = "";
      endTime_ = "";
      notes_ = "";
      listData_ = null;
      if (listDataBuilder_ != null) {
        listDataBuilder_.dispose();
        listDataBuilder_ = null;
      }
      internalGetMutableMapListData().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.grpcinterface.GetDataProto.internal_static_financedata_DataResponse_descriptor;
    }

    @java.lang.Override
    public io.grpc.grpcinterface.DataResponse getDefaultInstanceForType() {
      return io.grpc.grpcinterface.DataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.grpcinterface.DataResponse build() {
      io.grpc.grpcinterface.DataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.grpcinterface.DataResponse buildPartial() {
      io.grpc.grpcinterface.DataResponse result = new io.grpc.grpcinterface.DataResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.grpc.grpcinterface.DataResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.startTime_ = startTime_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endTime_ = endTime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.notes_ = notes_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.listData_ = listDataBuilder_ == null
            ? listData_
            : listDataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.mapListData_ = internalGetMapListData();
        result.mapListData_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.grpcinterface.DataResponse) {
        return mergeFrom((io.grpc.grpcinterface.DataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.grpcinterface.DataResponse other) {
      if (other == io.grpc.grpcinterface.DataResponse.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getStartTime().isEmpty()) {
        startTime_ = other.startTime_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEndTime().isEmpty()) {
        endTime_ = other.endTime_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getNotes().isEmpty()) {
        notes_ = other.notes_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasListData()) {
        mergeListData(other.getListData());
      }
      internalGetMutableMapListData().mergeFrom(
          other.internalGetMapListData());
      bitField0_ |= 0x00000020;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              startTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              endTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              notes_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getListDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, io.grpc.grpcinterface.ListOfString>
              mapListData__ = input.readMessage(
                  MapListDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMapListData().getMutableMap().put(
                  mapListData__.getKey(), mapListData__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object startTime_ = "";
    /**
     * <code>string startTime = 2;</code>
     * @return The startTime.
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string startTime = 2;</code>
     * @return The bytes for startTime.
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string startTime = 2;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      startTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string startTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      startTime_ = getDefaultInstance().getStartTime();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string startTime = 2;</code>
     * @param value The bytes for startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      startTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object endTime_ = "";
    /**
     * <code>string endTime = 3;</code>
     * @return The endTime.
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string endTime = 3;</code>
     * @return The bytes for endTime.
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string endTime = 3;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      endTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string endTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      endTime_ = getDefaultInstance().getEndTime();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string endTime = 3;</code>
     * @param value The bytes for endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      endTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object notes_ = "";
    /**
     * <code>string notes = 4;</code>
     * @return The notes.
     */
    public java.lang.String getNotes() {
      java.lang.Object ref = notes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string notes = 4;</code>
     * @return The bytes for notes.
     */
    public com.google.protobuf.ByteString
        getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string notes = 4;</code>
     * @param value The notes to set.
     * @return This builder for chaining.
     */
    public Builder setNotes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      notes_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string notes = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotes() {
      notes_ = getDefaultInstance().getNotes();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string notes = 4;</code>
     * @param value The bytes for notes to set.
     * @return This builder for chaining.
     */
    public Builder setNotesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      notes_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private io.grpc.grpcinterface.ListOfString listData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.grpcinterface.ListOfString, io.grpc.grpcinterface.ListOfString.Builder, io.grpc.grpcinterface.ListOfStringOrBuilder> listDataBuilder_;
    /**
     * <code>.financedata.ListOfString listData = 5;</code>
     * @return Whether the listData field is set.
     */
    public boolean hasListData() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.financedata.ListOfString listData = 5;</code>
     * @return The listData.
     */
    public io.grpc.grpcinterface.ListOfString getListData() {
      if (listDataBuilder_ == null) {
        return listData_ == null ? io.grpc.grpcinterface.ListOfString.getDefaultInstance() : listData_;
      } else {
        return listDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.financedata.ListOfString listData = 5;</code>
     */
    public Builder setListData(io.grpc.grpcinterface.ListOfString value) {
      if (listDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        listData_ = value;
      } else {
        listDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.financedata.ListOfString listData = 5;</code>
     */
    public Builder setListData(
        io.grpc.grpcinterface.ListOfString.Builder builderForValue) {
      if (listDataBuilder_ == null) {
        listData_ = builderForValue.build();
      } else {
        listDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.financedata.ListOfString listData = 5;</code>
     */
    public Builder mergeListData(io.grpc.grpcinterface.ListOfString value) {
      if (listDataBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          listData_ != null &&
          listData_ != io.grpc.grpcinterface.ListOfString.getDefaultInstance()) {
          getListDataBuilder().mergeFrom(value);
        } else {
          listData_ = value;
        }
      } else {
        listDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.financedata.ListOfString listData = 5;</code>
     */
    public Builder clearListData() {
      bitField0_ = (bitField0_ & ~0x00000010);
      listData_ = null;
      if (listDataBuilder_ != null) {
        listDataBuilder_.dispose();
        listDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.financedata.ListOfString listData = 5;</code>
     */
    public io.grpc.grpcinterface.ListOfString.Builder getListDataBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getListDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.financedata.ListOfString listData = 5;</code>
     */
    public io.grpc.grpcinterface.ListOfStringOrBuilder getListDataOrBuilder() {
      if (listDataBuilder_ != null) {
        return listDataBuilder_.getMessageOrBuilder();
      } else {
        return listData_ == null ?
            io.grpc.grpcinterface.ListOfString.getDefaultInstance() : listData_;
      }
    }
    /**
     * <code>.financedata.ListOfString listData = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.grpcinterface.ListOfString, io.grpc.grpcinterface.ListOfString.Builder, io.grpc.grpcinterface.ListOfStringOrBuilder> 
        getListDataFieldBuilder() {
      if (listDataBuilder_ == null) {
        listDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.grpcinterface.ListOfString, io.grpc.grpcinterface.ListOfString.Builder, io.grpc.grpcinterface.ListOfStringOrBuilder>(
                getListData(),
                getParentForChildren(),
                isClean());
        listData_ = null;
      }
      return listDataBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, io.grpc.grpcinterface.ListOfString> mapListData_;
    private com.google.protobuf.MapField<java.lang.String, io.grpc.grpcinterface.ListOfString>
        internalGetMapListData() {
      if (mapListData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapListDataDefaultEntryHolder.defaultEntry);
      }
      return mapListData_;
    }
    private com.google.protobuf.MapField<java.lang.String, io.grpc.grpcinterface.ListOfString>
        internalGetMutableMapListData() {
      if (mapListData_ == null) {
        mapListData_ = com.google.protobuf.MapField.newMapField(
            MapListDataDefaultEntryHolder.defaultEntry);
      }
      if (!mapListData_.isMutable()) {
        mapListData_ = mapListData_.copy();
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return mapListData_;
    }
    public int getMapListDataCount() {
      return internalGetMapListData().getMap().size();
    }
    /**
     * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
     */
    @java.lang.Override
    public boolean containsMapListData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMapListData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapListDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString> getMapListData() {
      return getMapListDataMap();
    }
    /**
     * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString> getMapListDataMap() {
      return internalGetMapListData().getMap();
    }
    /**
     * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
io.grpc.grpcinterface.ListOfString getMapListDataOrDefault(
        java.lang.String key,
        /* nullable */
io.grpc.grpcinterface.ListOfString defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString> map =
          internalGetMapListData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
     */
    @java.lang.Override
    public io.grpc.grpcinterface.ListOfString getMapListDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString> map =
          internalGetMapListData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMapListData() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableMapListData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
     */
    public Builder removeMapListData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMapListData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString>
        getMutableMapListData() {
      bitField0_ |= 0x00000020;
      return internalGetMutableMapListData().getMutableMap();
    }
    /**
     * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
     */
    public Builder putMapListData(
        java.lang.String key,
        io.grpc.grpcinterface.ListOfString value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMapListData().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>map&lt;string, .financedata.ListOfString&gt; mapListData = 6;</code>
     */
    public Builder putAllMapListData(
        java.util.Map<java.lang.String, io.grpc.grpcinterface.ListOfString> values) {
      internalGetMutableMapListData().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:financedata.DataResponse)
  }

  // @@protoc_insertion_point(class_scope:financedata.DataResponse)
  private static final io.grpc.grpcinterface.DataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.grpcinterface.DataResponse();
  }

  public static io.grpc.grpcinterface.DataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataResponse>
      PARSER = new com.google.protobuf.AbstractParser<DataResponse>() {
    @java.lang.Override
    public DataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.grpcinterface.DataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

