// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/financedata.proto

package io.grpc.grpcinterface;

public interface DataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:financedata.DataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestData = 1;</code>
   */
  java.lang.String getRequestData();
  /**
   * <code>string requestData = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestDataBytes();
}
