// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/financedata.proto

package io.grpc.grpcinterface;

public final class GetDataProto {
  private GetDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financedata_DataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financedata_DataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financedata_DataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financedata_DataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/financedata.proto\022\013financedata\"\"" +
      "\n\013DataRequest\022\023\n\013requestData\030\001 \001(\t\"\037\n\014Da" +
      "taResponse\022\017\n\007message\030\001 \001(\t2K\n\007GetData\022@" +
      "\n\007GetData\022\030.financedata.DataRequest\032\031.fi" +
      "nancedata.DataResponse\"\000B-\n\025io.grpc.grpc" +
      "interfaceB\014GetDataProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_financedata_DataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_financedata_DataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financedata_DataRequest_descriptor,
        new java.lang.String[] { "RequestData", });
    internal_static_financedata_DataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_financedata_DataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financedata_DataResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
