// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financedata.proto

package io.grpc.grpcinterface2;

public final class GetDataProto2 {
  private GetDataProto2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financedata_DataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financedata_DataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financedata_DataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financedata_DataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021financedata.proto\022\013financedata\"U\n\013Data" +
      "Request\022\023\n\013requestData\030\001 \001(\t\022\021\n\tstartTim" +
      "e\030\002 \001(\t\022\017\n\007endTime\030\003 \001(\t\022\r\n\005notes\030\004 \001(\t\"" +
      "R\n\014DataResponse\022\017\n\007message\030\001 \001(\t\022\021\n\tstar" +
      "tTime\030\002 \001(\t\022\017\n\007endTime\030\003 \001(\t\022\r\n\005notes\030\004 " +
      "\001(\t2K\n\007GetData\022@\n\007GetData\022\030.financedata." +
      "DataRequest\032\031.financedata.DataResponse\"\000" +
      "B/\n\026io.grpc.grpcinterface2B\rGetDataProto" +
      "2P\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_financedata_DataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_financedata_DataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financedata_DataRequest_descriptor,
        new java.lang.String[] { "RequestData", "StartTime", "EndTime", "Notes", });
    internal_static_financedata_DataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_financedata_DataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financedata_DataResponse_descriptor,
        new java.lang.String[] { "Message", "StartTime", "EndTime", "Notes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
