name: Tag Trigger

on:
  push:
    tags:
      - 'service*/**'  # This triggers the workflow for any tag that starts with 'service' and has further parts

jobs:
  process-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up tags
        id: tags
        run: |
          # Get the current tag
          TAG_NAME=${GITHUB_REF##*/}

          # Split the tag by '/' and export parts as environment variables
          IFS='/' read -ra TAG_PARTS <<< "$TAG_NAME"
          echo "TAG_SERVICE=${TAG_PARTS[3]}" >> $GITHUB_ENV
          echo "TAG_MICROSERVICE=${TAG_PARTS[2]}" >> $GITHUB_ENV
          echo "TAG_ENV=${TAG_PARTS[1]}" >> $GITHUB_ENV
          echo "TAG_VERSION=${TAG_PARTS[0]}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ${{ env.TAG_SERVICE }}/Dockerfile  # Specify the path to the Dockerfile
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.TAG_SERVICE }}:${{ github.sha }}
