name: Tag Trigger

on:
  push:
    tags:
      - 'v*'  # This triggers the workflow for any tag that matches the pattern 'v*'

jobs:
  tag_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Tag ${GITHUB_REF} has been pushed!"